# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    inouire.register_user_listener:
        class: AppBundle\EventListener\RegisterUserListener
        arguments: ["@doctrine.orm.entity_manager","@twig","@swiftmailer.mailer"]
        tags:
            - { name: kernel.event_subscriber }

    inouire.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags: [{ name: "form.type" }]

    inouire.invitation.form.type:
        class: AppBundle\Form\Type\InvitationFormType
        arguments: ["@inouire.invitation.form.data_transformer"]
        tags: [{ name: "form.type" }]

    inouire.invitation.form.data_transformer:
        class: AppBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ["@doctrine.orm.entity_manager"]
