# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    inouire_mininet.attachment_locator.class: AppBundle\Service\AttachmentLocator
    inouire_mininet.thumbnailer.class: AppBundle\Service\Thumbnailer
    inouire_mininet.image_resize.class: AppBundle\Service\ImageResize
    inouire_mininet.image_upload.class: AppBundle\Service\ImageUpload
    inouire_mininet.sharelink_checker.class: AppBundle\Service\ShareLinkChecker

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    inouire.register_user_listener:
        class: AppBundle\EventListener\RegisterUserListener
        arguments: ["@doctrine.orm.entity_manager","@twig","@swiftmailer.mailer"]
        tags:
            - { name: kernel.event_subscriber }

    inouire.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags: [{ name: "form.type" }]

    inouire.invitation.form.type:
        class: AppBundle\Form\Type\InvitationFormType
        arguments: ["@inouire.invitation.form.data_transformer"]
        tags: [{ name: "form.type" }]

    inouire.invitation.form.data_transformer:
        class: AppBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    inouire.attachment_locator:
        class: "%inouire_mininet.attachment_locator.class%"
        arguments:
            - "%images_path%"
            - "%videos_path%"
        
    inouire.thumbnailer:
        class: "%inouire_mininet.thumbnailer.class%"
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@inouire.attachment_locator"
            
    inouire.image_resize:
        class: "%inouire_mininet.image_resize.class%"
        arguments:
            - "@inouire.attachment_locator"
        
    inouire.image_upload:
        class: "%inouire_mininet.image_upload.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@inouire.image_resize"
            - "@inouire.thumbnailer"
            - "@inouire.attachment_locator"
            
    inouire.sharelink_checker:
        class: "%inouire_mininet.sharelink_checker.class%"
        arguments:
            - "@doctrine.orm.entity_manager"