# admin routes

admin_invitations:
    path:  /invitations
    defaults: { _controller: AppBundle:Invitation:list }

admin_invite:
    path:  /invite
    requirements:
        _method:  POST
    defaults: { _controller: AppBundle:Invitation:invite }
    
admin_tags:
    path:  /tags
    defaults: { _controller: AppBundle:Tag:adminList }
